name: Check & test & build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    name: Quality & security checks
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true

      - name: Check out code
        uses: actions/checkout@v4

      - name: Lint Go Code
        run: make check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true

      - name: Check out code
        uses: actions/checkout@v4

      - name: Run unit tests with
        run: make run-example

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [check, test]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build
        run: make build